

alexjeeuh joined DisGhost Support & Hangout
[2024-07-27 23:14:41] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        NoneType: None

        =======================================================
        


apxangejl joined Îãðîìíàÿ êàëîâàÿ ìàññà
[2024-07-28 14:45:30] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        NoneType: None

        =======================================================
        
[2024-07-28 14:45:53] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        NoneType: None

        =======================================================
        
[2024-07-28 14:59:42] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        NoneType: None

        =======================================================
        
[2024-07-28 15:01:10] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        NoneType: None

        =======================================================
        
[2024-07-28 15:07:31] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        NoneType: None

        =======================================================
        
[2024-07-28 15:36:51] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 717, in invoke\n    await self.prepare(inter)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 314, in prepare\n    if not await self.can_run(inter):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in can_run\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 573, in async_all\n    for elem in gen:\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in <genexpr>\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n                           ^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\core.py", line 2499, in pred\n    raise NSFWChannelRequired(ch)  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "disnake.ext.commands.errors.NSFWChannelRequired: Channel 'â”Šãƒ»bot-commands' needs to be NSFW for this command to work.\n"]        
        =======================================================
        
[2024-07-28 15:37:59] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 717, in invoke\n    await self.prepare(inter)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 314, in prepare\n    if not await self.can_run(inter):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in can_run\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 573, in async_all\n    for elem in gen:\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in <genexpr>\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n                           ^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\core.py", line 2499, in pred\n    raise NSFWChannelRequired(ch)  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "disnake.ext.commands.errors.NSFWChannelRequired: Channel 'â”Šãƒ»bot-commands' needs to be NSFW for this command to work.\n"]        
        =======================================================
        
[2024-07-28 15:53:41] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 717, in invoke\n    await self.prepare(inter)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 314, in prepare\n    if not await self.can_run(inter):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in can_run\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 573, in async_all\n    for elem in gen:\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in <genexpr>\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n                           ^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\core.py", line 2122, in predicate\n    raise MissingPermissions(missing)\n', 'disnake.ext.commands.errors.MissingPermissions: You are missing Administrator permission(s) to run this command.\n']        
        =======================================================
        
[2024-07-28 16:21:20] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\testing.py", line 28, in button\n    button = Button(style=ButtonStyle.blurple, label="Click this")\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "TypeError: Button.__init__() got an unexpected keyword argument 'style'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', "disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Button.__init__() got an unexpected keyword argument 'style'\n"]        
        =======================================================
        


middlle. joined test ground
[2024-07-28 22:13:16] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ test ground::::::::::::::â•‘ middlle.:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 816985615811608616:::::â•‘ 162632274846810112::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 717, in invoke\n    await self.prepare(inter)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 314, in prepare\n    if not await self.can_run(inter):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in can_run\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 575, in async_all\n    elem = await elem\n           ^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\core.py", line 1848, in predicate\n    raise CheckAnyFailure(unwrapped, errors)\n', 'disnake.ext.commands.errors.CheckAnyFailure: You do not have permission to run this command.\n']        
        =======================================================
        
[2024-08-01 21:22:13] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['disnake.ext.commands.errors.CommandNotFound: Command "welcome" is not found\n']        
        =======================================================
        
[2024-08-01 21:24:19] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\testing.py", line 149, in select\n    await inter.response.send_message(embed=embede, view=view)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 210, in request\n    raise HTTPException(response, data)\n', 'disnake.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body\nIn data.components.0.components.0.options: Must be between 1 and 25 in length.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', 'disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body\nIn data.components.0.components.0.options: Must be between 1 and 25 in length.\n']        
        =======================================================
        
[2024-08-01 22:17:11] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 191, in about\n    cputype = cpuinfo.get_cpu_info()["model name"]\n            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n', "KeyError: 'model name'\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 217, in about\n    await inter.response.send_message(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', 'disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n']        
        =======================================================
        
[2024-08-01 22:18:36] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 215, in about\n    await inter.response.send_message(embed=embed)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 217, in about\n    await inter.response.send_message(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', 'disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n']        
        =======================================================
        
[2024-08-01 22:19:35] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 215, in about\n    await inter.response.send_message(embed=embed)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 217, in about\n    await inter.response.send_message(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', 'disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n']        
        =======================================================
        
[2024-08-01 22:25:34] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 229, in about\n    await inter.response.send_message(embed=embed)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 231, in about\n    await inter.response.send_message(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', 'disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n']        
        =======================================================
        
[2024-08-01 22:28:37] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 229, in about\n    await inter.response.send_message(embed=embed)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1023, in send_message\n    await adapter.create_interaction_response(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\webhook\\async_.py", line 208, in request\n    raise NotFound(response, data)\n', 'disnake.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 231, in about\n    await inter.response.send_message(\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\interactions\\base.py", line 1033, in send_message\n    raise InteractionTimedOut(self._parent) from e\n', 'disnake.errors.InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', 'disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: InteractionTimedOut: Interaction took more than 3 seconds to be responded to. Please defer it using "interaction.response.defer" on the start of your command. Later you may send a response by editing the deferred message using "interaction.edit_original_response"\nNote: This might also be caused by a misconfiguration in the components make sure you do not respond twice in case this is a component.\n']        
        =======================================================
        
[2024-08-01 22:44:59] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 717, in invoke\n    await self.prepare(inter)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 314, in prepare\n    if not await self.can_run(inter):\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in can_run\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 573, in async_all\n    for elem in gen:\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\base_core.py", line 623, in <genexpr>\n    return await async_all(predicate(inter) for predicate in predicates)  # type: ignore\n                           ^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\core.py", line 2499, in pred\n    raise NSFWChannelRequired(ch)  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "disnake.ext.commands.errors.NSFWChannelRequired: Channel 'â”Šãƒ»bot-commands' needs to be NSFW for this command to work.\n"]        
        =======================================================
        
[2024-08-01 22:48:05] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 207, in about\n    cputype = self.callget_cpu_inf()\n              ^^^^^^^^^^^^^^^^^^^^\n', "AttributeError: 'General' object has no attribute 'callget_cpu_inf'. Did you mean: 'callget_cpu_info'?\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 253, in about\n    await inter.edit_original_response(embed=embed,ephemeral=True)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "TypeError: Interaction.edit_original_response() got an unexpected keyword argument 'ephemeral'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', "disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Interaction.edit_original_response() got an unexpected keyword argument 'ephemeral'\n"]        
        =======================================================
        
[2024-08-01 22:49:03] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 207, in about\n    cputype = self.callget_cpu_inf()\n              ^^^^^^^^^^^^^^^^^^^^\n', "AttributeError: 'General' object has no attribute 'callget_cpu_inf'. Did you mean: 'callget_cpu_info'?\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 253, in about\n    await inter.edit_original_response(embed=embed,ephemeral=True)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "TypeError: Interaction.edit_original_response() got an unexpected keyword argument 'ephemeral'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', "disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Interaction.edit_original_response() got an unexpected keyword argument 'ephemeral'\n"]        
        =======================================================
        
[2024-08-01 22:52:26] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['Traceback (most recent call last):\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 207, in about\n    cputype = self.callget_cpu_inf()\n              ^^^^^^^^^^^^^^^^^^^^\n', "AttributeError: 'General' object has no attribute 'callget_cpu_inf'. Did you mean: 'callget_cpu_info'?\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 728, in invoke\n    await call_param_func(self.callback, inter, self.cog, **kwargs)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\params.py", line 1083, in call_param_func\n    return await maybe_coroutine(safe_call, function, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\utils.py", line 567, in maybe_coroutine\n    return await value\n           ^^^^^^^^^^^\n', '  File "D:\\source\\helia\\src\\listener\\general.py", line 253, in about\n    await inter.edit_original_response(embed=embed,delete_after=30)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', "TypeError: Interaction.edit_original_response() got an unexpected keyword argument 'delete_after'\n", '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\interaction_bot_base.py", line 1378, in process_application_commands\n    await app_command.invoke(interaction)\n', '  File "C:\\Users\\andrej\\AppData\\Roaming\\Python\\Python312\\site-packages\\disnake\\ext\\commands\\slash_core.py", line 737, in invoke\n    raise CommandInvokeError(exc) from exc\n', "disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Interaction.edit_original_response() got an unexpected keyword argument 'delete_after'\n"]        
        =======================================================
        
[2024-08-01 23:38:55] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ Space Quest 4 Bots(Test Bot area)::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘        
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 438848185008390158:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback 
        ['disnake.ext.commands.errors.CommandNotFound: Command "debug" is not found\n']        
        =======================================================
        
[2024-08-02 15:10:52] Slash Command Description Lengths:
```Cog: Preferences, Command: prefix, 
 Description Length: 20```
```Cog: Preferences, Command: locale, 
 Description Length: 17```
```Cog: Help, Command: help, 
 Description Length: 19```
```Cog: testingCOG, Command: button, 
 Description Length: 11```
```Cog: Moderation, Command: ban, 
 Description Length: 10```
```Cog: Moderation, Command: unban, 
 Description Length: 12```
```Cog: Moderation, Command: multiban, 
 Description Length: 12```
```Cog: Moderation, Command: kick, 
 Description Length: 11```
```Cog: Moderation, Command: purge, 
 Description Length: 14```
```Cog: Moderation, Command: setname, 
 Description Length: 12```
```Cog: Moderation, Command: mute, 
 Description Length: 11```
```Cog: Moderation, Command: unmute, 
 Description Length: 13```
```Cog: Moderation, Command: lockdownrole, 
 Description Length: 13```
```Cog: Moderation, Command: unlockrole, 
 Description Length: 11```
```Cog: Moderation, Command: lockdown, 
 Description Length: 15```
```Cog: Moderation, Command: unlock, 
 Description Length: 13```
```Cog: Moderation, Command: channellock, 
 Description Length: 12```
```Cog: Moderation, Command: channelunlock, 
 Description Length: 14```
```Cog: Calculator, Command: calculator, 
 Description Length: 10```
```Cog: Admin, Command: load, 
 Description Length: 14```
```Cog: Admin, Command: unload, 
 Description Length: 16```
```Cog: Admin, Command: reload, 
 Description Length: 16```
```Cog: Admin, Command: invite_bot, 
 Description Length: 43```
```Cog: Admin, Command: set_status, 
 Description Length: 36```
```Cog: Admin, Command: invite, 
 Description Length: 17```
```Cog: Admin, Command: uptime, 
 Description Length: 11```
```Cog: Admin, Command: shutdown, 
 Description Length: 35```
```Cog: Utilities, Command: user, 
 Description Length: 9```
```Cog: Utilities, Command: emoji, 
 Description Length: 10```
```Cog: Utilities, Command: channel, 
 Description Length: 12```
```Cog: Utilities, Command: avatar, 
 Description Length: 11```
```Cog: Utilities, Command: randint, 
 Description Length: 6```
```Cog: Utilities, Command: sqrt, 
 Description Length: 4```
```Cog: Utilities, Command: guild, 
 Description Length: 5```
```Cog: GNULinux, Command: arch, 
 Description Length: 4```
```Cog: GNULinux, Command: ubuntu, 
 Description Length: 6```
```Cog: GNULinux, Command: debian, 
 Description Length: 6```
```Cog: GNULinux, Command: deepin, 
 Description Length: 6```
```Cog: GNULinux, Command: manjaro, 
 Description Length: 7```
```Cog: GNULinux, Command: mint, 
 Description Length: 4```
```Cog: General, Command: echo, 
 Description Length: 4```
```Cog: General, Command: embed, 
 Description Length: 5```
```Cog: General, Command: wiki, 
 Description Length: 9```
```Cog: General, Command: about, 
 Description Length: 5```
```Cog: General, Command: privacy, 
 Description Length: 7```
```Cog: Broadcast, Command: announce, 
 Description Length: 8```
```Cog: Broadcast, Command: debug, 
 Description Length: 5```
```Cog: Minigames, Command: kubik, 
 Description Length: 11```
```Cog: Minigames, Command: monetka, 
 Description Length: 9```
```Cog: Minigames, Command: casino, 
 Description Length: 3```
```Cog: Other, Command: ping, 
 Description Length: 10```
```Cog: Other, Command: wallpaper, 
 Description Length: 13```
```Cog: Welcome, Command: welcome, 
 Description Length: 7```
```Cog: Goodbye, Command: goodbye, 
 Description Length: 4```
```Cog: Goodbye, Command: goodbye_channel, 
 Description Length: 3```
```Cog: Goodbye, Command: goodbye_clear, 
 Description Length: 5```
```Cog: Goodbye, Command: goodbye_text, 
 Description Length: 3```
[2024-08-02 15:41:48] 
        â•‘========================â•‘=========================â•‘
        â•‘ Guild                  â•‘ Member                  â•‘
        â•‘ DisGhost Support & Hangout::::::::::::::â•‘ lumina.ri:::::::::::::::::â•‘
        â•‘========================â•‘=========================â•‘
        â•‘ Guild ID               â•‘ Member ID               â•‘
        â•‘ 534450100890763302:::::â•‘ 540142383270985738::::::â•‘
        â•‘========================â•‘=========================â•‘
        =======================================================
        Traceback
        ['disnake.ext.commands.errors.CommandNotFound: Command "jsk" is not found\n']
        =======================================================
        
